### ISSUE TITLE
Journaling for retries

### ISSUE THREAD

**Issue by nikita-volkov** [nikita-volkov/hasql-transaction#14]
Conflicts can only happen when the whole monad has ran (and commit finally happens).

If they need to be retried the logic can submit exactly the same inputs to the backend without retrying the monad.

If that exact inputs can't be committed again (due to DB inconsistencies), it should fail.

In practice this would hold onto memory for inputs a bit longer, but allow much more interesting uses of transactions.

_Originally posted by @domenkozar in https://github.com/nikita-volkov/hasql-transaction/issues/7#issuecomment-679180470_

**Comment by nikita-volkov** [comment]
@domenkozar 

Oooh! This sounds like a very insightful idea! :) So cache all the executed queries with their parameters and, instead of reexecuting the original monad, simply reexecute them all in case of a conflict? This is something definitely worth researching!

A possible blocker though here is that it may not be the case that a conflicting transaction only fails when committed. If I recall correctly, the DB may be emitting transactional errors amidst an unfinished transaction. We have to check on that.

**Comment by bitc** [comment]
If I understand what is written here, then this is not correct (at least for SERIALIZABLE isolation level), and will give incorrect results.

The simplest example is a transaction that increments a counter (table has only 1 row):

    prevCount <- exec "SELECT val FROM counter" []
    exec "UPDATE counter SET val = $1" [prevCount + 1]

Now imagine that two processes run the above transaction concurrently.

The first succeeds (for example incrementing the counter 1 -> 2).
But PostgreSQL may give me a serialization failure on the second. If i simply rerun the exact same queries then I can end up with a final incorrect counter value of 2. What we need to do is rerun the "business logic" so that it SELECTS the updated counter value (now 2) and then increments that, resulting in the correct result of 3

**Comment by nikita-volkov** [comment]
Thanks for posting that! Explains why we shouldn't do that. Closing the issue unless someone comes up with a counterargument.
